create table if not exists public.restaurants (
  id integer generated by default as identity primary key,

  name text not null,
  address text,
  city text,
  restaurant_description text,
  cover_image_path text,

  owner_id integer not null,

  -- 1 = active, 2 = inactive, 0 = suspended
  status smallint not null default 1,
  constraint restaurants_status_check check (status in (0, 1, 2)),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- id

-- Type: int4 (aka integer)

-- Default: Identity / auto-increment (toggle “Is Identity” if shown, or set as “Generated”)

-- Primary key: ✅

-- Not null: ✅

-- name

-- Type: text (or varchar(255))

-- Not null: ✅ (recommended)

-- address

-- Type: text

-- city

-- Type: text

-- restaurant_description

-- Type: text

-- owner_id

-- Type: int4 (aka integer)

-- Not null: (optional, depends on your logic)